# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
# Text to speech
tts:
  - platform: google_translate

logger:
  default: warning
  logs:
    custom_components.damper: debug

# frontend:
#   development_repo: /workspaces/frontend/

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

panel_custom:
  - name: damper-panel
    # url_path needs to be unique for each panel_custom config
    url_path: damper-panel
    sidebar_title: Damper Panel
    sidebar_icon: mdi:server
    module_url: /local/damper-panel.js
    config:
      # Data you want to make available to panel
      hello: world
  - name: damper-panel-ts
    # url_path needs to be unique for each panel_custom config
    url_path: damper-panel-ts
    sidebar_title: Damper Panel TS
    sidebar_icon: mdi:server
    module_url: /local/damper-panel-ts.ts
    config:
      # Data you want to make available to panel
      hello: world
