# Example services.yaml entry

set_timer:
  # Description of the service
  description: Sets timer. [PoC for services]
  # Different fields that your service accepts
  fields:
    # Key of the field
    entity_id:
      # Description of the field
      description: Name(s) of the entities to set
      # Example value that can be passed for this field
      example: "cover.modbus_1"
    sleep_time:
      description: Sleep time in seconds
      example: "10"

test_damper:
  # Description of the service
  description: Starts a test run of the damper (Close -> Open) and measures runtimes and power against the defined thresholds
  # Different fields that your service accepts
  fields:
    # Key of the field
    entity_id:
      # Description of the field
      description: Name(s) of the damper (=cover) entities to test
      # Example value that can be passed for this field
      example: "cover.modbus_1"
